-- Jalankan sekali pada project Supabase yang sudah memiliki data.
-- Nilai HPP transaksi lama diestimasi dari harga beli barang saat migrasi;
-- nilai historis sebelum migrasi tidak dapat diketahui dari skema lama.

ALTER TABLE public.detail_penjualan
ADD COLUMN IF NOT EXISTS harga_beli_satuan NUMERIC(14,2);

UPDATE public.detail_penjualan AS detail
SET harga_beli_satuan = barang.harga_beli
FROM public.barang AS barang
WHERE detail.barang_id = barang.id
  AND detail.harga_beli_satuan IS NULL;

ALTER TABLE public.detail_penjualan
ALTER COLUMN harga_beli_satuan SET NOT NULL;

CREATE TABLE IF NOT EXISTS public.beban_operasional (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal DATE NOT NULL DEFAULT CURRENT_DATE,
    kategori VARCHAR(100) NOT NULL,
    keterangan TEXT NOT NULL,
    jumlah NUMERIC(14,2) NOT NULL CHECK (jumlah > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_beban_operasional_tanggal
ON public.beban_operasional (tanggal);

ALTER TABLE public.beban_operasional ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "beban_select_anon" ON public.beban_operasional;
DROP POLICY IF EXISTS "beban_insert_anon" ON public.beban_operasional;

CREATE POLICY "beban_select_anon"
ON public.beban_operasional FOR SELECT TO anon USING (true);

CREATE POLICY "beban_insert_anon"
ON public.beban_operasional FOR INSERT TO anon WITH CHECK (true);

CREATE OR REPLACE FUNCTION public.create_sale(
    p_header JSONB,
    p_details JSONB
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY INVOKER
AS $$
DECLARE
    v_penjualan_id BIGINT;
    v_detail JSONB;
    v_harga_beli NUMERIC(14,2);
BEGIN
    IF p_details IS NULL OR jsonb_array_length(p_details) = 0 THEN
        RAISE EXCEPTION 'Detail penjualan tidak boleh kosong.';
    END IF;

    INSERT INTO public.penjualan (
        nomor_faktur, tanggal, pelanggan_id, subtotal, diskon, pajak, total, metode_pembayaran
    )
    VALUES (
        p_header->>'nomor_faktur',
        COALESCE((p_header->>'tanggal')::TIMESTAMPTZ, NOW()),
        NULLIF(p_header->>'pelanggan_id', '')::BIGINT,
        COALESCE((p_header->>'subtotal')::NUMERIC, 0),
        COALESCE((p_header->>'diskon')::NUMERIC, 0),
        COALESCE((p_header->>'pajak')::NUMERIC, 0),
        COALESCE((p_header->>'total')::NUMERIC, 0),
        COALESCE(NULLIF(p_header->>'metode_pembayaran', ''), 'Tunai')
    )
    RETURNING id INTO v_penjualan_id;

    FOR v_detail IN SELECT * FROM jsonb_array_elements(p_details)
    LOOP
        SELECT harga_beli
        INTO v_harga_beli
        FROM public.barang
        WHERE id = (v_detail->>'barang_id')::BIGINT;

        IF v_harga_beli IS NULL THEN
            RAISE EXCEPTION 'Barang dengan ID % tidak ditemukan.', v_detail->>'barang_id';
        END IF;

        INSERT INTO public.detail_penjualan (
            penjualan_id, barang_id, qty, harga_satuan, harga_beli_satuan, diskon
        )
        VALUES (
            v_penjualan_id,
            (v_detail->>'barang_id')::BIGINT,
            (v_detail->>'qty')::INTEGER,
            (v_detail->>'harga_satuan')::NUMERIC,
            v_harga_beli,
            COALESCE((v_detail->>'diskon')::NUMERIC, 0)
        );
    END LOOP;

    RETURN v_penjualan_id;
END;
$$;
