-- ============================================================
-- SIA PENJUALAN & PERSEDIAAN TOKO RETAIL
-- Supabase PostgreSQL
-- ============================================================

-- Bersihkan objek lama jika ingin instalasi ulang.
DROP TRIGGER IF EXISTS trg_detail_penjualan_stok ON public.detail_penjualan;
DROP FUNCTION IF EXISTS public.fn_update_stok();
DROP FUNCTION IF EXISTS public.create_sale(jsonb, jsonb);

DROP TABLE IF EXISTS public.detail_penjualan CASCADE;
DROP TABLE IF EXISTS public.penjualan CASCADE;
DROP TABLE IF EXISTS public.pelanggan CASCADE;
DROP TABLE IF EXISTS public.barang CASCADE;

-- ============================================================
-- 1. TABEL BARANG
-- ============================================================
CREATE TABLE public.barang (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode_barang VARCHAR(30) NOT NULL UNIQUE,
    nama_barang VARCHAR(150) NOT NULL,
    kategori VARCHAR(100),
    satuan VARCHAR(30) NOT NULL DEFAULT 'pcs',
    harga_beli NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (harga_beli >= 0),
    harga_jual NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (harga_jual >= 0),
    stok INTEGER NOT NULL DEFAULT 0 CHECK (stok >= 0),
    stok_minimum INTEGER NOT NULL DEFAULT 0 CHECK (stok_minimum >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 2. TABEL PELANGGAN
-- ============================================================
CREATE TABLE public.pelanggan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode_pelanggan VARCHAR(30) NOT NULL UNIQUE,
    nama_pelanggan VARCHAR(150) NOT NULL,
    no_telepon VARCHAR(30),
    alamat TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 3. HEADER PENJUALAN
-- ============================================================
CREATE TABLE public.penjualan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor_faktur VARCHAR(40) NOT NULL UNIQUE,
    tanggal TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    pelanggan_id BIGINT REFERENCES public.pelanggan(id) ON DELETE SET NULL,
    subtotal NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
    diskon NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (diskon >= 0),
    pajak NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (pajak >= 0),
    total NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (total >= 0),
    metode_pembayaran VARCHAR(30) NOT NULL DEFAULT 'Tunai',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 4. DETAIL PENJUALAN
-- ============================================================
CREATE TABLE public.detail_penjualan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    penjualan_id BIGINT NOT NULL REFERENCES public.penjualan(id) ON DELETE CASCADE,
    barang_id BIGINT NOT NULL REFERENCES public.barang(id),
    qty INTEGER NOT NULL CHECK (qty > 0),
    harga_satuan NUMERIC(14,2) NOT NULL CHECK (harga_satuan >= 0),
    harga_beli_satuan NUMERIC(14,2) NOT NULL CHECK (harga_beli_satuan >= 0),
    diskon NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (diskon >= 0),
    subtotal NUMERIC(14,2) GENERATED ALWAYS AS ((qty * harga_satuan) - diskon) STORED,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 5. BEBAN OPERASIONAL
-- ============================================================
CREATE TABLE public.beban_operasional (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal DATE NOT NULL DEFAULT CURRENT_DATE,
    kategori VARCHAR(100) NOT NULL,
    keterangan TEXT NOT NULL,
    jumlah NUMERIC(14,2) NOT NULL CHECK (jumlah > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- UPDATED_AT
-- ============================================================
CREATE OR REPLACE FUNCTION public.fn_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_barang_updated_at ON public.barang;
CREATE TRIGGER trg_barang_updated_at
BEFORE UPDATE ON public.barang
FOR EACH ROW
EXECUTE FUNCTION public.fn_set_updated_at();

-- ============================================================
-- TRIGGER STOK
-- Setiap detail penjualan yang masuk akan mengurangi stok barang.
-- Validasi stok dilakukan secara atomik untuk mencegah stok minus.
-- ============================================================
CREATE OR REPLACE FUNCTION public.fn_update_stok()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_stok INTEGER;
BEGIN
    SELECT stok
    INTO v_stok
    FROM public.barang
    WHERE id = NEW.barang_id
    FOR UPDATE;

    IF v_stok IS NULL THEN
        RAISE EXCEPTION 'Barang dengan ID % tidak ditemukan.', NEW.barang_id;
    END IF;

    IF v_stok < NEW.qty THEN
        RAISE EXCEPTION
            'Stok tidak cukup untuk barang ID %. Stok tersedia: %, permintaan: %.',
            NEW.barang_id, v_stok, NEW.qty;
    END IF;

    UPDATE public.barang
    SET stok = stok - NEW.qty,
        updated_at = NOW()
    WHERE id = NEW.barang_id;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_detail_penjualan_stok
BEFORE INSERT ON public.detail_penjualan
FOR EACH ROW
EXECUTE FUNCTION public.fn_update_stok();

-- ============================================================
-- FUNCTION TRANSAKSI PENJUALAN ATOMIK
-- Frontend memanggil RPC ini sehingga header + detail + trigger
-- berjalan dalam satu transaksi database.
--
-- p_header contoh:
-- {
--   "nomor_faktur": "INV-20261002-001",
--   "pelanggan_id": 1,
--   "subtotal": 10000,
--   "diskon": 0,
--   "pajak": 0,
--   "total": 10000,
--   "metode_pembayaran": "Tunai"
-- }
--
-- p_details contoh:
-- [
--   {"barang_id":1,"qty":2,"harga_satuan":5000,"diskon":0}
-- ]
-- ============================================================
CREATE OR REPLACE FUNCTION public.create_sale(
    p_header JSONB,
    p_details JSONB
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY INVOKER
AS $$
DECLARE
    v_penjualan_id BIGINT;
    v_detail JSONB;
    v_harga_beli NUMERIC(14,2);
BEGIN
    IF p_details IS NULL OR jsonb_array_length(p_details) = 0 THEN
        RAISE EXCEPTION 'Detail penjualan tidak boleh kosong.';
    END IF;

    INSERT INTO public.penjualan (
        nomor_faktur,
        tanggal,
        pelanggan_id,
        subtotal,
        diskon,
        pajak,
        total,
        metode_pembayaran
    )
    VALUES (
        p_header->>'nomor_faktur',
        COALESCE((p_header->>'tanggal')::TIMESTAMPTZ, NOW()),
        NULLIF(p_header->>'pelanggan_id', '')::BIGINT,
        COALESCE((p_header->>'subtotal')::NUMERIC, 0),
        COALESCE((p_header->>'diskon')::NUMERIC, 0),
        COALESCE((p_header->>'pajak')::NUMERIC, 0),
        COALESCE((p_header->>'total')::NUMERIC, 0),
        COALESCE(NULLIF(p_header->>'metode_pembayaran', ''), 'Tunai')
    )
    RETURNING id INTO v_penjualan_id;

    FOR v_detail IN SELECT * FROM jsonb_array_elements(p_details)
    LOOP
        SELECT harga_beli
        INTO v_harga_beli
        FROM public.barang
        WHERE id = (v_detail->>'barang_id')::BIGINT;

        IF v_harga_beli IS NULL THEN
            RAISE EXCEPTION 'Barang dengan ID % tidak ditemukan.', v_detail->>'barang_id';
        END IF;

        INSERT INTO public.detail_penjualan (
            penjualan_id,
            barang_id,
            qty,
            harga_satuan,
            harga_beli_satuan,
            diskon
        )
        VALUES (
            v_penjualan_id,
            (v_detail->>'barang_id')::BIGINT,
            (v_detail->>'qty')::INTEGER,
            (v_detail->>'harga_satuan')::NUMERIC,
            v_harga_beli,
            COALESCE((v_detail->>'diskon')::NUMERIC, 0)
        );
    END LOOP;

    RETURN v_penjualan_id;
END;
$$;

-- ============================================================
-- INDEX
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_barang_nama
ON public.barang (nama_barang);

CREATE INDEX IF NOT EXISTS idx_penjualan_tanggal
ON public.penjualan (tanggal);

CREATE INDEX IF NOT EXISTS idx_detail_penjualan_penjualan
ON public.detail_penjualan (penjualan_id);

CREATE INDEX IF NOT EXISTS idx_detail_penjualan_barang
ON public.detail_penjualan (barang_id);

CREATE INDEX IF NOT EXISTS idx_beban_operasional_tanggal
ON public.beban_operasional (tanggal);

-- ============================================================
-- RLS
-- Untuk aplikasi belajar/local development.
-- Jika aplikasi akan dipublikasikan, ganti kebijakan ini dengan
-- autentikasi dan authorization yang lebih ketat.
-- ============================================================
ALTER TABLE public.barang ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pelanggan ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.penjualan ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.detail_penjualan ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.beban_operasional ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "barang_select_anon" ON public.barang;
DROP POLICY IF EXISTS "barang_insert_anon" ON public.barang;
DROP POLICY IF EXISTS "barang_update_anon" ON public.barang;
DROP POLICY IF EXISTS "barang_delete_anon" ON public.barang;

CREATE POLICY "barang_select_anon"
ON public.barang FOR SELECT TO anon USING (true);

CREATE POLICY "barang_insert_anon"
ON public.barang FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "barang_update_anon"
ON public.barang FOR UPDATE TO anon USING (true) WITH CHECK (true);

CREATE POLICY "barang_delete_anon"
ON public.barang FOR DELETE TO anon USING (true);

DROP POLICY IF EXISTS "pelanggan_select_anon" ON public.pelanggan;
DROP POLICY IF EXISTS "pelanggan_insert_anon" ON public.pelanggan;
DROP POLICY IF EXISTS "pelanggan_update_anon" ON public.pelanggan;
DROP POLICY IF EXISTS "pelanggan_delete_anon" ON public.pelanggan;

CREATE POLICY "pelanggan_select_anon"
ON public.pelanggan FOR SELECT TO anon USING (true);

CREATE POLICY "pelanggan_insert_anon"
ON public.pelanggan FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "pelanggan_update_anon"
ON public.pelanggan FOR UPDATE TO anon USING (true) WITH CHECK (true);

CREATE POLICY "pelanggan_delete_anon"
ON public.pelanggan FOR DELETE TO anon USING (true);

DROP POLICY IF EXISTS "penjualan_select_anon" ON public.penjualan;
DROP POLICY IF EXISTS "penjualan_insert_anon" ON public.penjualan;

CREATE POLICY "penjualan_select_anon"
ON public.penjualan FOR SELECT TO anon USING (true);

CREATE POLICY "penjualan_insert_anon"
ON public.penjualan FOR INSERT TO anon WITH CHECK (true);

DROP POLICY IF EXISTS "detail_select_anon" ON public.detail_penjualan;
DROP POLICY IF EXISTS "detail_insert_anon" ON public.detail_penjualan;

CREATE POLICY "detail_select_anon"
ON public.detail_penjualan FOR SELECT TO anon USING (true);

CREATE POLICY "detail_insert_anon"
ON public.detail_penjualan FOR INSERT TO anon WITH CHECK (true);

DROP POLICY IF EXISTS "beban_select_anon" ON public.beban_operasional;
DROP POLICY IF EXISTS "beban_insert_anon" ON public.beban_operasional;

CREATE POLICY "beban_select_anon"
ON public.beban_operasional FOR SELECT TO anon USING (true);

CREATE POLICY "beban_insert_anon"
ON public.beban_operasional FOR INSERT TO anon WITH CHECK (true);

-- ============================================================
-- DATA CONTOH (opsional)
-- Jalankan bagian ini jika ingin langsung mencoba aplikasi.
-- ============================================================
INSERT INTO public.pelanggan (kode_pelanggan, nama_pelanggan, no_telepon, alamat)
VALUES
('CUST-001', 'Pelanggan Umum', '-', '-')
ON CONFLICT (kode_pelanggan) DO NOTHING;

INSERT INTO public.barang
(kode_barang, nama_barang, kategori, satuan, harga_beli, harga_jual, stok, stok_minimum)
VALUES
('BRG-001', 'Beras Premium 5 Kg', 'Sembako', 'sak', 65000, 75000, 20, 5),
('BRG-002', 'Minyak Goreng 1 Liter', 'Sembako', 'botol', 15000, 18000, 30, 5),
('BRG-003', 'Gula Pasir 1 Kg', 'Sembako', 'kg', 14000, 17000, 25, 5)
ON CONFLICT (kode_barang) DO NOTHING;

-- ============================================================
-- CATATAN:
-- Supabase Dashboard -> SQL Editor -> paste file ini -> Run.
-- ============================================================
